name: UltimateServerProtector
version: 21.0
author: Overwrite
main: ru.overwrite.protect.bukkit.ServerProtector
api-version: 1.13
folia-supported: true
commands:
   ultimateserverprotector:
      aliases: [usp, serverprotector]