name: '${project.name}'
version: '${project.version}'
author: OverwriteMC
main: ru.overwrite.protect.bukkit.ServerProtector
api-version: 1.13
folia-supported: true
load-priority: STARTUP
loadafter: [LuckPerms, BungeeGuard]
softdepend: [PlaceholderAPI]
commands:
   ultimateserverprotector:
      aliases: [usp, serverprotector]
permissions:
  serverprotector.admin:
    children:
      serverprotector.reload: true
      serverprotector.reboot: true
      serverprotector.encrypt: true
      serverprotector.setpass: true
      serverprotector.addop: true
      serverprotector.addip: true
      serverprotector.rempass: true
      serverprotector.remop: true
      serverprotector.remip: true