name: '${name}'
version: '${version}'
author: OverwriteMC
main: ru.overwrite.protect.bukkit.ServerProtector
api-version: 1.13
folia-supported: true
load-priority: STARTUP
loadafter: [LuckPerms, BungeeGuard]
commands:
   ultimateserverprotector:
      aliases: [usp, serverprotector]