name: Java CI (Gradle)

on:
  push:
    branches:
      - main

jobs:
  build:

    if: "! contains(toJSON(github.event.commits.*.message), '[SKIP-CI]')"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build with Gradle | EN
        run: ./gradlew clean shadowJar -Plang=en
      - uses: actions/upload-artifact@v4
        with:
          name: UltimateServerProtector (English)
          path: build/libs/UltimateServerProtector-v*-en.jar

      - name: Build with Gradle | RU
        run: ./gradlew clean shadowJar -Plang=ru
      - uses: actions/upload-artifact@v4
        with:
          name: UltimateServerProtector (Russian)
          path: build/libs/UltimateServerProtector-v*-ru.jar
